# Generated by Django 2.0.6 on 2018-07-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_games_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
