# Generated by Django 2.0.6 on 2018-07-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180728_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
